### ISSUE TITLE
Governance proposal templates are outdated

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/documentation#427] opened 2022-12-13 10:47 UTC
## Description

There's been some significant changes to the proposal forms on Token but the example templates that are linked to the documents are still using outdated templates.

E.g.
https://docs.vega.xyz/testnet/tutorials/proposals/new-market-proposal

The example template for `Token dApp (JSON)` still contains title and description as well as timestamps which are now separate fields in the proposal forms as seen in:
https://token.fairground.wtf/governance/propose/new-market

Some fields for the proposals might have also changed since the document was last updated.

**Comment by edd** [comment] 2022-12-13 13:16
Closing as this is not valid. What I think is the issue is that the JSON is not the right structure for the form in Governance, rather than the structure has changed. We'll catch up on what we need to generate for the form, and create a new ticket if it seems like the right way to go.

**Closed by edd** 2022-12-13 13:16 UTC
Labels: 🐛 bug, documentation
