### ISSUE TITLE
Turn on Network switcher in navigation

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/documentation#257] opened 2022-09-17 14:29 UTC
Find a way to navigate between Mainnet and Testnet docs
Example of what docusaurus already does and can be turned on when we're ready https://nymtech.net/docs/next/overview/

https://github.com/vegaprotocol/documentation/issues/116 - enable navigation

**Comment by candida-d** [comment] 2022-10-31 11:46
Closing as a duplicate of #116

**Closed by candida-d** 2022-10-31 11:46 UTC
Labels: documentation
